/**
 * Chat operations.
 *
 * All Firestore writes go through these helpers so the data model
 * (deterministic conversation IDs for 1:1, denormalized `participants`
 * on messages, unread counters, typing indicators) stays consistent.
 *
 * Conversation IDs:
 *   - Private (1:1):  `[uidA, uidB].sort().join("_")` — both participants
 *                     derive the same id so duplicates are impossible.
 *   - Group:          Auto-generated by Firestore via addDoc.
 *
 * Messages carry a denormalized `participants` array so security rules
 * can validate `list` queries without expensive parent-document reads.
 */

import {
  addDoc,
  arrayUnion,
  arrayRemove,
  collection,
  doc,
  getDoc,
  increment,
  serverTimestamp,
  setDoc,
  updateDoc,
  writeBatch,
} from "firebase/firestore";
import {
  ref as storageRef,
  uploadBytes,
  getDownloadURL,
} from "firebase/storage";
import { db, storage } from "@/lib/firebase";

const CONVERSATIONS = "conversations";
const MESSAGES = "messages";

/* ── Helpers ──────────────────────────────────────────────────── */

export function conversationIdFor(uidA, uidB) {
  return [uidA, uidB].sort().join("_");
}

function zeroedUnreadCounts(uids) {
  return Object.fromEntries(uids.map((u) => [u, 0]));
}

/* ── Conversation creation ────────────────────────────────────── */

/**
 * Idempotently ensure a private (1:1) conversation exists between
 * two users. Returns the deterministic conversation id.
 */
export async function ensurePrivateConversation(uidA, uidB) {
  if (!uidA || !uidB) throw new Error("Saknar användare.");
  if (uidA === uidB) throw new Error("Kan inte chatta med dig själv.");

  const id = conversationIdFor(uidA, uidB);
  const ref = doc(db, CONVERSATIONS, id);
  const snap = await getDoc(ref);
  if (!snap.exists()) {
    const participants = [uidA, uidB].sort();
    await setDoc(ref, {
      type: "private",
      participants,
      unreadCounts: zeroedUnreadCounts(participants),
      typing: {},
      createdAt: serverTimestamp(),
      lastMessageAt: serverTimestamp(),
    });
  }
  return id;
}

/**
 * Create a new group conversation. Caller is automatically added to
 * `participants`. Returns the new conversation id.
 *
 * @param {string} creatorUid
 * @param {string} name
 * @param {string[]} otherUids — at least one
 */
export async function createGroupConversation(creatorUid, name, otherUids) {
  if (!creatorUid) throw new Error("Inte inloggad.");
  const trimmed = (name || "").trim();
  if (!trimmed) throw new Error("Gruppen måste ha ett namn.");
  if (trimmed.length > 80) throw new Error("Gruppnamnet är för långt.");
  if (!Array.isArray(otherUids) || otherUids.length < 1) {
    throw new Error("Välj minst en deltagare.");
  }

  const participants = Array.from(new Set([creatorUid, ...otherUids]));
  const ref = await addDoc(collection(db, CONVERSATIONS), {
    type: "group",
    participants,
    groupName: trimmed,
    createdBy: creatorUid,
    unreadCounts: zeroedUnreadCounts(participants),
    typing: {},
    createdAt: serverTimestamp(),
    lastMessageAt: serverTimestamp(),
  });
  return ref.id;
}

/* ── Group management ─────────────────────────────────────────── */

export async function renameGroup(convId, newName) {
  const trimmed = (newName || "").trim();
  if (!trimmed) throw new Error("Gruppnamn krävs.");
  if (trimmed.length > 80) throw new Error("Gruppnamnet är för långt.");
  await updateDoc(doc(db, CONVERSATIONS, convId), {
    groupName: trimmed,
  });
}

export async function addGroupParticipants(convId, newUids) {
  if (!Array.isArray(newUids) || newUids.length === 0) return;
  const updates = { participants: arrayUnion(...newUids) };
  newUids.forEach((u) => {
    updates[`unreadCounts.${u}`] = 0;
  });
  await updateDoc(doc(db, CONVERSATIONS, convId), updates);
}

export async function leaveGroup(convId, myUid) {
  if (!convId || !myUid) return;
  await updateDoc(doc(db, CONVERSATIONS, convId), {
    participants: arrayRemove(myUid),
    [`unreadCounts.${myUid}`]: 0,
    [`typing.${myUid}`]: null,
  });
}

/* ── Sending messages ─────────────────────────────────────────── */

/**
 * Send a text message. `participants` MUST be the conversation's full
 * participants array — caller is responsible for passing it through
 * (they get it from the loaded conversation doc, or compute it from
 * the conversationId for private chats).
 *
 * The function:
 *   - Adds the message (with denormalized participants for rules)
 *   - Updates conversation lastMessage + lastMessageAt
 *   - Increments unreadCount for every participant EXCEPT sender
 *   - Resets sender's own unreadCount
 *   - Clears sender's typing flag
 */
export async function sendTextMessage(convId, senderUid, participants, text) {
  const trimmed = (text || "").trim();
  if (!trimmed) return;
  if (trimmed.length > 4000) throw new Error("Meddelandet är för långt.");
  if (!convId || !senderUid || !participants) {
    throw new Error("Saknar conversation-data.");
  }

  const convRef = doc(db, CONVERSATIONS, convId);
  const messagesCol = collection(convRef, MESSAGES);

  const msgRef = await addDoc(messagesCol, {
    senderUid,
    participants,
    type: "text",
    text: trimmed,
    seenBy: [senderUid],
    createdAt: serverTimestamp(),
  });

  const updates = {
    lastMessage: {
      text: trimmed,
      senderUid,
      type: "text",
      createdAt: serverTimestamp(),
    },
    lastMessageAt: serverTimestamp(),
    [`unreadCounts.${senderUid}`]: 0,
    [`typing.${senderUid}`]: null,
  };
  participants.forEach((uid) => {
    if (uid !== senderUid) {
      updates[`unreadCounts.${uid}`] = increment(1);
    }
  });

  await updateDoc(convRef, updates);
  return msgRef.id;
}

/**
 * Upload to Storage and create a file/image message.
 */
export async function sendFileMessage(
  convId,
  senderUid,
  participants,
  file,
  { onProgress } = {}
) {
  if (!file) throw new Error("Ingen fil vald.");
  if (file.size > 25 * 1024 * 1024) {
    throw new Error("Filen får max vara 25 MB.");
  }
  if (!convId || !senderUid || !participants) {
    throw new Error("Saknar conversation-data.");
  }

  const isImage = file.type.startsWith("image/");

  onProgress?.(10);
  const path = `chats/${convId}/${Date.now()}-${file.name}`;
  const fileRef = storageRef(storage, path);
  await uploadBytes(fileRef, file);
  onProgress?.(70);

  const fileUrl = await getDownloadURL(fileRef);
  onProgress?.(85);

  const convRef = doc(db, CONVERSATIONS, convId);
  const messagesCol = collection(convRef, MESSAGES);

  await addDoc(messagesCol, {
    senderUid,
    participants,
    type: isImage ? "image" : "file",
    text: "",
    fileUrl,
    fileName: file.name,
    fileSize: file.size,
    fileType: file.type,
    seenBy: [senderUid],
    createdAt: serverTimestamp(),
  });

  const updates = {
    lastMessage: {
      text: isImage ? "📷 Bild" : `📎 ${file.name}`,
      senderUid,
      type: isImage ? "image" : "file",
      createdAt: serverTimestamp(),
    },
    lastMessageAt: serverTimestamp(),
    [`unreadCounts.${senderUid}`]: 0,
    [`typing.${senderUid}`]: null,
  };
  participants.forEach((uid) => {
    if (uid !== senderUid) {
      updates[`unreadCounts.${uid}`] = increment(1);
    }
  });

  await updateDoc(convRef, updates);
  onProgress?.(100);
}

/* ── Read receipts ────────────────────────────────────────────── */

/**
 * Mark all received messages as seen by `myUid` and reset my unread
 * counter on the conversation. Best-effort — silently swallows per-
 * message failures so opening a chat never throws.
 */
export async function markConversationRead(convId, myUid, messages) {
  if (!convId || !myUid) return;

  const convRef = doc(db, CONVERSATIONS, convId);
  try {
    await updateDoc(convRef, { [`unreadCounts.${myUid}`]: 0 });
  } catch (err) {
    console.warn("unreadCounts reset failed:", err?.code);
  }

  if (!messages || messages.length === 0) return;
  const toMark = messages.filter(
    (m) => m.senderUid !== myUid && !(m.seenBy || []).includes(myUid)
  );
  if (toMark.length === 0) return;

  const batch = writeBatch(db);
  toMark.forEach((m) => {
    const msgRef = doc(db, CONVERSATIONS, convId, MESSAGES, m.id);
    batch.update(msgRef, { seenBy: arrayUnion(myUid) });
  });
  try {
    await batch.commit();
  } catch (err) {
    console.warn("markRead batch failed:", err?.code);
  }
}

/* ── Typing indicators ────────────────────────────────────────── */

export async function setTyping(convId, myUid) {
  if (!convId || !myUid) return;
  try {
    await updateDoc(doc(db, CONVERSATIONS, convId), {
      [`typing.${myUid}`]: serverTimestamp(),
    });
  } catch (err) {
    if (err?.code !== "not-found") {
      console.warn("setTyping failed:", err?.code);
    }
  }
}

export async function clearTyping(convId, myUid) {
  if (!convId || !myUid) return;
  try {
    await updateDoc(doc(db, CONVERSATIONS, convId), {
      [`typing.${myUid}`]: null,
    });
  } catch {
    /* noop */
  }
}
